INSERT INTO aluno (nome_aluno, biografia, linkedin, foto) VALUES
('Karine Verneque', 'Tenho 27 anos e sou Arquiteta de Automação de Testes atualmente. Iniciei na área de tecnologia como Desenvolvedora front-end aos 25 anos e a partir daí ví um mundo enorme de oportunidades, foi então buscando melhorar iniciei meu Bacharelado na área de Ciência de Dados na UNIVESP e cada dia que passo vejo o quanto a área de Tecnologia da informação continua em constante crescimento.', 'https://www.linkedin.com/in/karine-verneque','images/Karine_Verneque_RaKkbxA_4uWO7js.jpg'),
('Marcia Rocha', 'Especialista de BI, mãe do Juan e da Eloísa e apaixonada por esse mundo de TI e Ciências de Dados. Estou sempre em busca de novos conhecimentos e de saber sobre as novidades do universo de Tecnologia, principalmente no que se refere a análise de dados. No Bacharelado de Ciência de Dados da Univesp vi a oportunidade de agregar ainda mais conhecimento.', 'https://www.linkedin.com/in/maria-marcia-m-t-rocha','images/Marcia_Rocha_C4qbKCQ.jpeg'),
('Elizete Lacerda', 'Analista de Planejamento, atuo há 12 anos em finanças e estou me aventurando nesse mundo da tecnologia! Mãe de duas meninas sei bem a importância de um mundo com mais inclusão para mulheres.', 'https://www.linkedin.com/in/elizeteslacerda/','images/Elizete_B8JB6J1.jpg'),
('Iara Vieira', 'Analista de Faturamento e Auditoria de Telecom. Acredito que é sempre tempo para recomeçar, aos 46 anos de idade vejo no curso de Bacharelado de Ciências de Dados a oportunidade para transição carreira.', 'https://www.linkedin.com/in/iara-vieira-94b17832/','images/Iara_27nRGaP.jpg'),
('Otávio Muffo', 'Coordenador de Suporte e Implantação de Sistemas, formado em Química Bacharel, atuo há 12 anos em um software house detentora de um sistema de gestão de laboratórios (LIMS). O interesse no curso de Engenharia de Computação está em aprofundar os conhecimentos técnicos na minha área de atuação.','https://www.linkedin.com/in/ot%C3%A1vio-muffo-moreira-5b50a917b/', 'images/OtavioMuffo.jfif'),
('Gislaine', 'Biografia','linkedin', 'images/foto'),
('Rubens', 'Biografia','linkedin', 'images/foto')
;


INSERT INTO site (nome_site, home_page, descricao, logo) VALUES 
('Dio', 'https://www.dio.me/', 'A Digital Innovation One disponibiliza cursos, bootcamps e projetos práticos focados no mercado de trabalho. Há cursos gratuitos e pagos.', 'images/logo-dio_6VifTI0.png'),
('Laboratoria', 'https://hub.laboratoria.la/br', 'A Laboratória possibilita que mulheres que sonham com um futuro melhor comecem uma carreira transformadora e promissora na área de tecnologia.', 'images/logo_laboratoria_A6Qt5t9.png'),
('DSA', 'https://www.datascienceacademy.com.br/', 'Maior plataforma da América Latinade ensino online de Ciência de Dados, Big Data, Inteligência Artificial e Blockchain com cursos gratuitos e pagos.', 'images/dsa_WL7eQUO.png'),
('{reprograma}', 'https://reprograma.com.br/index.html', 'Iniciativa de impacto social que foca em ensinar programação para mulheres cis e trans que não têm recursos e/ou oportunidades para aprender a programar.', 'images/reprograma-fundos-claros_dfYsV0O.png'),
('ela empoder@.', 'https://elaempodera.softex.br/', 'Iniciativa com o objetivo de promover o empoderamento feminino nas comunidades empreendedoras, através de capacitações e mentorias, impulsionando negócios com a presença de mulheres em sua fundação e/ou em cargos de liderança.', 'images/ela_6Ux9ytL.png'),
('MaisMulheres.Tech', 'https://maismulheres.tech/', 'Uma parceria entre Microsoft e WoMakersCode, oferece trilhas de capacitação gratuita e online, nas áreas de Computação em Nuvem, Infraestrutura, Segurança da Informação, DevOps, Desenvolvimento e Ciência de Dados e Inteligência Artificial.', 'images/womakerscode_bQSqnxk.png'),
('Hands On Study', 'https://ead.handson.org.br/courses', 'Plataforma de educação para o mercado digital e capacitação profissional da Hands On Aceleradora. Oferta trilhas de capacitação com aulas em Desenvolvimento Profissional e Empresarial, Gestão de Negócios e muito mais.', 'images/hand_lUyJ6K4.png'),
('Google Ateliê Digital', 'https://learndigital.withgoogle.com/ateliedigital/courses', 'Encontre diversos conteúdos de aprendizagem gratuitos que ajudarão a expandir seus negócios ou alavancar sua carreira. Você pode selecionar módulos individuais ou fazer um curso inteiro, se preferir.', 'images/google-atelie_fVJrxpE.png'),
('Brasil Mais Digital', 'http://brasilmaisdigital.org.br/index.php/pt-br/cursos-online/dashboard-cursos', 'O Brasil Mais Digital é um projeto inovador e dinâmico de educação a distância que atua em três pontos essenciais da formação profissional: conhecimento, capacitação e oportunidades.', 'images/brasildigital_scDdf9F.png'),
('Coursera', 'https://www.coursera.org/courses?query=free', 'Tenha aquela sensação de "preparado para qualquer coisa" com mais de 5 mil cursos, certificações profissionais e diplomas de universidades e empresas de classe mundial.', 'images/coursera_1esbXod_EhsC78C_VjsL41y.png'),
('Microsoft Lear', 'https://docs.microsoft.com/pt-br/learn/', 'Se está apenas começando ou é um profissional experiente, nossa abordagem prática ajuda você a alcançar sua meta mais rapidamente, com mais confiança e no seu próprio ritmo.', 'images/microsoft_s19libW.png'),
('EV.G', 'https://www.escolavirtual.gov.br/catalogo', 'Cursos on-line e gratuitos de várias áreas de conhecimento para o desenvolvimento da Administração Pública e da Sociedade.', 'images/evg_5tc4eMd.png'),
('Fundação Bradesco', 'https://www.ev.org.br/cursos', 'A Fundação Bradesco tem uma escola virtual com cursos gratuitos, com certificado, nas áreas de Administração, Contabilidade e Finanças, Desenvolvimento, Educação Básica e Pedagogia e Informática.', 'images/ev_nqO4Sze.png')
;